server:
    port: 8887

spring:
    # MySQL
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/history_platform?useUnicode=true&useSSL=true&characterEncoding=utf8
        username: root
        password: 123456
        druid:
            initial-size: 1
            min-idle: 1
            max-active: 20
            test-on-borrow: true
            stat-view-servlet:
                allow: true

    # Security
    security:
        user:
            name: CSL
            password: 1234
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

# MyBatis-Plus
mybatis-plus:
    configuration:
        # 配置日志
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            # 表默认前缀
            table-prefix: h_
            # 统一的主键生成策略
            id-type: auto
    # 配置数据返回类型别名
    type-aliases-package: com.history.entity
    # 配置映射文件
    mapper-locations: classpath:mapper/*.xml

# JWT
jwt:
    # JWT 存储的请求头
    tokenHeader: Authorization
    # JWT 加密使用的密钥
    secret: history-platform-secret
    # JWT 的超时期限时间（60*60*24）
    expiration: 604800
    # JWT 负载中拿到开头
    tokenHead: Bearer

# Pagehelper


# 静态资源服务器配置信息
storage:
    ip: localhost
    port: ${server.port}
    # 当前项目的绝对目录
    abs-path: /Users/walker/Projects/History/
    # 静态文件存放的绝对目录
    path: ${storage.abs-path}/history-server/src/main/resources/static/files/
